### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by prashanthparsi** [ezioguga/cdktf-demo#1]
Where did you configured the AWS credentials while running the cdktf deploy? I get access denied even after ensuring the valid credentials in $HOME/.aws/credentials

**Comment by ezioguga** [comment]
Step1:
can you verify the user where you have generated these credentials have the correct access to spin up the EC2 instance in your account?
Step2:
verify the aws cli using simple command like aws s3 ls whether it's working correctly.

can you share the actual error message here to better understand the context?

**Comment by prashanthparsi** [comment]
Yes, the credentials are correct and I did aws sts get-caller-identity and it returns the correct identity. Also, aws s3 ls prints the basic bucket list from S3.

This is what I get - 
cdk-demo-instance-dev  Initializing the backend...


1 Stack deploying     0 Stacks done     0 Stacks waiting
cdk-demo-instance-dev  Error refreshing state: AccessDenied: Access Denied
                       status code: 403, request id: GMFRFF6YSAFSRTWP, host id: rwmq7snmTOJpmvLbHTjjmL+svd2OWtGDDYENGMYNeA0VmqqhaC3s9g90G43iPlwyVwSqMd6KkLI=


1 Stack deploying     0 Stacks done     0 Stacks waiting
non-zero exit code 1


Where does it takes the account credentials from? With plain vanilla terraform, it takes from the aws store credentials from local box. Any thoughts?

**Comment by ezioguga** [comment]
credentials are picked from the .aws folder. I think issue is related to the backend initializing. can you comment out the line 10-14 in ec2-stack.ts if this not working try removing the state file and run it again.

 Ref: https://stackoverflow.com/questions/61851903/how-to-solve-error-loading-state-accessdenied-access-denied-status-code-403-w

**Comment by prashanthparsi** [comment]
Never mind, I am good now.

cdk-demo-instance-dev  aws_instance.DEV-CDKTF-EC2 (DEV-CDKTF-EC2): Creating...
cdk-demo-instance-dev  aws_instance.DEV-CDKTF-EC2 (DEV-CDKTF-EC2): Still creating... [10s elapsed]
cdk-demo-instance-dev  aws_instance.DEV-CDKTF-EC2 (DEV-CDKTF-EC2): Still creating... [20s elapsed]
cdk-demo-instance-dev  aws_instance.DEV-CDKTF-EC2 (DEV-CDKTF-EC2): Still creating... [30s elapsed]
cdk-demo-instance-dev  aws_instance.DEV-CDKTF-EC2 (DEV-CDKTF-EC2): Still creating... [40s elapsed]
cdk-demo-instance-dev  aws_instance.DEV-CDKTF-EC2 (DEV-CDKTF-EC2): Creation complete after 42s [id=i-04682ba0f6ced2ac2]
cdk-demo-instance-dev  
                       Apply complete! Resources: 1 added, 0 changed, 0 destroyed.


Did couple of things - 
1) Ensured the backend s3 bucket is existing
2) also added subnetId in the EC2 stack to ensure it is created in the right VPC.

**Comment by ezioguga** [comment]
Thank you for letting me know. I forgot to mention that I have created the bucket before hand.
